// Onboarding questionnaire spec — source of truth for the /onboarding page.
// Per the design brief: 5-7 minutes for first session, deepens over time via ask_later.
// Order: easy/concrete -> reflective.

export type QuestionType =
  | "single_select"
  | "multi_select"
  | "slider"
  | "image_grid"
  | "free_text"
  | "measurement";

export type Option = { value: string; label: string; hint?: string };

export type Question = {
  id: string;
  prompt: string;
  type: QuestionType;
  options?: Option[];
  unit?: string;
  min?: number;
  max?: number;
  placeholder?: string;
  skip_allowed: boolean;
  ask_later: boolean;
  rationale: string;
  branching?: { skip_if?: { question_id: string; equals?: string; includes?: string } };
  followup_if_unsure?: Question[];
};

export type Section = {
  id: string;
  title: string;
  purpose: string;
  questions: Question[];
};

export const QUESTIONNAIRE: { sections: Section[] } = {
  sections: [
    {
      id: "body_fit",
      title: "Body & Fit",
      purpose:
        "Sets silhouette and proportion guardrails. Drives which cuts to favor, which to avoid, and which areas to balance.",
      questions: [
        {
          id: "height",
          prompt: "How tall are you?",
          type: "measurement",
          unit: "in",
          min: 48,
          max: 84,
          placeholder: "e.g. 65",
          skip_allowed: true,
          ask_later: false,
          rationale: "Affects proportion judgments — midi vs maxi, hem hits, scale of patterns.",
        },
        {
          id: "body_shape",
          prompt: "Which body shape best describes you?",
          type: "single_select",
          options: [
            { value: "pear", label: "Pear", hint: "Hips wider than shoulders, narrower waist" },
            { value: "hourglass", label: "Hourglass", hint: "Bust and hips balanced, defined waist" },
            { value: "apple", label: "Apple", hint: "Fuller midsection, slimmer legs" },
            { value: "rectangle", label: "Rectangle", hint: "Bust, waist, and hips similar widths" },
            { value: "inverted_triangle", label: "Inverted triangle", hint: "Shoulders wider than hips" },
            { value: "not_sure", label: "I'm not sure", hint: "We'll guide you" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale:
            "Primary driver of silhouette balance — what to highlight, skim, structure.",
          followup_if_unsure: [
            {
              id: "body_shape_helper",
              prompt:
                "When you stand straight in front of a mirror, where does your body feel widest?",
              type: "single_select",
              options: [
                { value: "shoulders", label: "Shoulders / chest" },
                { value: "waist", label: "Waist / midsection" },
                { value: "hips", label: "Hips / thighs" },
                { value: "even", label: "Pretty even top to bottom" },
              ],
              skip_allowed: true,
              ask_later: false,
              rationale: "Heuristic to infer body shape when self-ID is uncertain.",
            },
          ],
        },
        {
          id: "highlight_areas",
          prompt: "Which features do you like to highlight?",
          type: "multi_select",
          options: [
            { value: "shoulders", label: "Shoulders / collarbone" },
            { value: "waist", label: "Waist" },
            { value: "arms", label: "Arms" },
            { value: "legs", label: "Legs" },
            { value: "decolletage", label: "Décolletage" },
            { value: "hips_curves", label: "Hips / curves" },
            { value: "back", label: "Back" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Tells the stylist where to draw the eye.",
        },
        {
          id: "skim_areas",
          prompt: "Which areas do you prefer to skim or cover?",
          type: "multi_select",
          options: [
            { value: "upper_arms", label: "Upper arms" },
            { value: "midsection", label: "Midsection" },
            { value: "thighs", label: "Thighs" },
            { value: "hips", label: "Hips" },
            { value: "chest", label: "Chest" },
            { value: "calves", label: "Calves" },
            { value: "none", label: "No strong preference" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Constraint set: avoid silhouettes that emphasize these areas.",
        },
        {
          id: "fit_top",
          prompt: "How do you generally like tops to fit?",
          type: "single_select",
          options: [
            { value: "fitted", label: "Fitted" },
            { value: "semi_fitted", label: "Semi-fitted" },
            { value: "relaxed", label: "Relaxed" },
            { value: "oversized", label: "Oversized" },
            { value: "depends", label: "Depends on the day" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Top-half default. Combined with bottom_fit to enforce volume balance.",
        },
        {
          id: "fit_bottom",
          prompt: "How do you generally like bottoms to fit?",
          type: "single_select",
          options: [
            { value: "fitted", label: "Fitted / skinny" },
            { value: "straight", label: "Straight" },
            { value: "relaxed", label: "Relaxed / wide" },
            { value: "high_rise", label: "Always high-rise" },
            { value: "depends", label: "Depends on the day" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Bottom-half default. Pairs with fit_top for proportion rules.",
        },
        {
          id: "fit_dress",
          prompt: "How do you generally like dresses to fit?",
          type: "single_select",
          options: [
            { value: "fitted", label: "Fitted / bodycon" },
            { value: "defined_waist", label: "Defined waist, flowy skirt" },
            { value: "shift", label: "Shift / straight" },
            { value: "flowy", label: "Loose / flowy" },
            { value: "rarely_wear", label: "I rarely wear dresses" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Dress silhouette default.",
        },
        {
          id: "shoe_size",
          prompt: "What's your shoe size? (US women's)",
          type: "free_text",
          placeholder: "e.g. 8.5",
          skip_allowed: true,
          ask_later: false,
          rationale: "Future feature: suggesting items to fill gaps.",
        },
        {
          id: "comfort_constraints",
          prompt: "Anything that affects comfort or what you can wear?",
          type: "multi_select",
          options: [
            { value: "no_heels", label: "Heels are uncomfortable / I avoid them" },
            { value: "no_tight_waistbands", label: "Tight waistbands bother me" },
            { value: "no_tags", label: "Tags / scratchy fabrics bother me" },
            { value: "wool_sensitive", label: "Wool / itchy fibers bother me" },
            { value: "needs_stretch", label: "I need stretch in everything" },
            { value: "mobility", label: "Mobility consideration (please note below)" },
            { value: "none", label: "None of the above" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Hard constraints. Drops items violating these from suggestions.",
        },
        {
          id: "comfort_constraints_note",
          prompt: "Anything else about comfort we should know?",
          type: "free_text",
          placeholder: "Optional",
          skip_allowed: true,
          ask_later: false,
          rationale: "Catch-all for constraints not in the list above.",
        },
        {
          id: "measurements",
          prompt: "Measurements (optional, helps with fit)",
          type: "free_text",
          placeholder: "Bust / Waist / Hip / Inseam, e.g. 36/28/40/30",
          skip_allowed: true,
          ask_later: true,
          rationale: "Fine-grained fit tuning. Not needed for daily suggestions on day 1.",
        },
        {
          id: "bra_support",
          prompt: "Chest support needs?",
          type: "single_select",
          options: [
            { value: "minimal", label: "Minimal — bralettes are fine" },
            { value: "standard", label: "Standard support" },
            { value: "full", label: "I need full support / structure" },
            { value: "skip", label: "Prefer not to say" },
          ],
          skip_allowed: true,
          ask_later: true,
          rationale: "Affects strappy/backless tops, certain necklines.",
        },
      ],
    },
    {
      id: "coloring",
      title: "Coloring",
      purpose:
        "Sets the color palette: which hues flatter near the face, which to push to bottoms or skip entirely.",
      questions: [
        {
          id: "seasonal_palette",
          prompt: "Do you know your seasonal color palette?",
          type: "single_select",
          options: [
            { value: "deep_autumn", label: "Deep Autumn" },
            { value: "soft_autumn", label: "Soft Autumn" },
            { value: "warm_autumn", label: "Warm Autumn" },
            { value: "deep_winter", label: "Deep Winter" },
            { value: "cool_winter", label: "Cool Winter" },
            { value: "clear_winter", label: "Clear Winter / Bright Winter" },
            { value: "light_spring", label: "Light Spring" },
            { value: "warm_spring", label: "Warm Spring" },
            { value: "clear_spring", label: "Clear / Bright Spring" },
            { value: "light_summer", label: "Light Summer" },
            { value: "cool_summer", label: "Cool Summer" },
            { value: "soft_summer", label: "Soft Summer" },
            { value: "not_sure", label: "I'm not sure", hint: "We'll figure it out together" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale:
            "If known, it's the single best color signal. If unsure, we infer from undertone + contrast.",
          followup_if_unsure: [
            {
              id: "vein_color",
              prompt:
                "Look at the veins on the inside of your wrist in natural light. What color are they?",
              type: "single_select",
              options: [
                { value: "blue_purple", label: "Blue or purple", hint: "Suggests cool undertone" },
                { value: "green", label: "Green", hint: "Suggests warm undertone" },
                { value: "mix", label: "Hard to tell / a mix", hint: "Suggests neutral" },
              ],
              skip_allowed: true,
              ask_later: false,
              rationale: "Self-test for undertone.",
            },
            {
              id: "jewelry_pref",
              prompt: "Which metal flatters your skin most?",
              type: "single_select",
              options: [
                { value: "silver", label: "Silver / white gold / platinum", hint: "Cool" },
                { value: "gold", label: "Yellow gold / brass / copper", hint: "Warm" },
                { value: "both", label: "Both look good", hint: "Neutral" },
              ],
              skip_allowed: true,
              ask_later: false,
              rationale: "Self-test for undertone.",
            },
            {
              id: "sun_reaction",
              prompt: "How does your skin react to sun?",
              type: "single_select",
              options: [
                { value: "burns", label: "Burns easily, rarely tans" },
                { value: "tans_to_pink", label: "Burns first, then tans pink" },
                { value: "tans_warm", label: "Tans easily to a warm golden brown" },
                { value: "deep", label: "Deep skin tone year-round" },
              ],
              skip_allowed: true,
              ask_later: false,
              rationale: "Confirms undertone and value level.",
            },
          ],
        },
        {
          id: "hair_color",
          prompt: "Current hair color (including any color or highlights)",
          type: "single_select",
          options: [
            { value: "black", label: "Black" },
            { value: "dark_brown", label: "Dark brown" },
            { value: "medium_brown", label: "Medium brown" },
            { value: "light_brown", label: "Light brown" },
            { value: "auburn_red", label: "Auburn / red" },
            { value: "blonde", label: "Blonde" },
            { value: "grey_silver", label: "Grey / silver" },
            { value: "highlighted", label: "Highlighted / multi-tone" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Affects contrast and what tones pull her face forward vs back.",
        },
        {
          id: "eye_color",
          prompt: "Eye color",
          type: "single_select",
          options: [
            { value: "brown_dark", label: "Dark brown / black" },
            { value: "brown_warm", label: "Warm brown / hazel" },
            { value: "green", label: "Green" },
            { value: "blue", label: "Blue" },
            { value: "grey", label: "Grey" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Adds nuance to palette and contrast.",
        },
        {
          id: "contrast_level",
          prompt: "How would you describe your overall contrast (skin vs hair vs eyes)?",
          type: "image_grid",
          options: [
            { value: "high", label: "High contrast", hint: "e.g. dark hair + light skin" },
            { value: "medium", label: "Medium contrast", hint: "Tones blend somewhat" },
            { value: "low", label: "Low contrast", hint: "Hair, skin, eyes are similar in depth" },
            { value: "not_sure", label: "Not sure" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "High-contrast people look best in high-contrast outfits, etc.",
        },
        {
          id: "best_colors",
          prompt: "Colors you feel best in (as many as you want)",
          type: "free_text",
          placeholder: "e.g. rust, terracotta, forest, espresso",
          skip_allowed: true,
          ask_later: false,
          rationale: "Direct positive signal for the AI to lean on.",
        },
        {
          id: "avoid_colors",
          prompt: "Colors that wash you out or you avoid",
          type: "free_text",
          placeholder: "e.g. baby blue, mint, dusty pink",
          skip_allowed: true,
          ask_later: false,
          rationale: "Hard negative signal.",
        },
      ],
    },
    {
      id: "lifestyle",
      title: "Lifestyle & Calendar",
      purpose:
        "Maps outfit needs to how you actually spend your time — so we don't suggest blazers if you're WFH all week.",
      questions: [
        {
          id: "city",
          prompt: "What city are you in?",
          type: "free_text",
          placeholder: "e.g. Los Gatos, CA",
          skip_allowed: true,
          ask_later: false,
          rationale: "Drives weather lookup. Used directly in the morning suggestion.",
        },
        {
          id: "profession",
          prompt: "What do you do for work?",
          type: "free_text",
          placeholder: "e.g. Product Manager",
          skip_allowed: true,
          ask_later: false,
          rationale: "Sets formality baseline and vocabulary.",
        },
        {
          id: "work_environment",
          prompt: "What's your typical work environment?",
          type: "single_select",
          options: [
            { value: "wfh", label: "Fully remote / WFH" },
            { value: "hybrid", label: "Hybrid" },
            { value: "in_office", label: "In-office most days" },
            { value: "client_facing", label: "Client / customer-facing" },
            { value: "on_feet", label: "On my feet / physical" },
            { value: "uniform", label: "I wear a uniform" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Top-level branch for office-dress-code questions.",
        },
        {
          id: "office_dress_code",
          prompt: "Office dress code?",
          type: "single_select",
          options: [
            { value: "casual", label: "Casual" },
            { value: "smart_casual", label: "Smart casual / business casual" },
            { value: "business", label: "Business / formal" },
            { value: "creative", label: "Creative / no rules" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Sets the floor and ceiling for formality on workdays.",
          branching: { skip_if: { question_id: "work_environment", equals: "wfh" } },
        },
        {
          id: "week_breakdown",
          prompt: "Roughly, what does a typical week look like? (pick all that apply)",
          type: "multi_select",
          options: [
            { value: "office", label: "Office / work meetings" },
            { value: "wfh_calls", label: "WFH on video calls" },
            { value: "parenting", label: "Parenting / caregiving" },
            { value: "workouts", label: "Workouts / gym / yoga" },
            { value: "errands", label: "Errands / school runs" },
            { value: "social", label: "Casual social (brunch, friends)" },
            { value: "date_nights", label: "Date nights / dinners" },
            { value: "formal_events", label: "Formal events (occasional)" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Distribution of outfit jobs the wardrobe needs to cover.",
        },
        {
          id: "travel_frequency",
          prompt: "How often do you travel?",
          type: "single_select",
          options: [
            { value: "rarely", label: "Rarely" },
            { value: "few_times_year", label: "A few times a year" },
            { value: "monthly", label: "Roughly monthly" },
            { value: "frequent", label: "Frequent / business traveler" },
          ],
          skip_allowed: true,
          ask_later: true,
          rationale: "Future feature: pack-friendly suggestions, capsule outfits.",
        },
        {
          id: "life_stage",
          prompt:
            "Anything currently affecting your body or wardrobe? (Optional — helps tune suggestions)",
          type: "multi_select",
          options: [
            { value: "pregnant", label: "Pregnant" },
            { value: "postpartum", label: "Postpartum" },
            { value: "nursing", label: "Nursing" },
            { value: "body_changing", label: "Body shape recently changed" },
            { value: "perimenopause", label: "Perimenopause / temperature regulation" },
            { value: "none", label: "None of the above" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Adjusts fit, layering, and fabric recommendations sensitively.",
        },
      ],
    },
    {
      id: "constraints",
      title: "Hard Constraints",
      purpose:
        "Absolute no-gos. The stylist treats these as filters, not preferences — they will never be suggested.",
      questions: [
        {
          id: "never_colors",
          prompt: "Colors you'll never wear",
          type: "free_text",
          placeholder: "e.g. neon, baby blue, true black",
          skip_allowed: true,
          ask_later: false,
          rationale: "Hard filter.",
        },
        {
          id: "never_silhouettes",
          prompt: "Silhouettes or items you'll never wear",
          type: "free_text",
          placeholder: "e.g. mini skirts, crop tops, tapered hip pants",
          skip_allowed: true,
          ask_later: false,
          rationale: "Hard filter on silhouette.",
        },
        {
          id: "never_fabrics",
          prompt: "Fabrics you avoid",
          type: "multi_select",
          options: [
            { value: "wool", label: "Wool / itchy" },
            { value: "polyester", label: "100% polyester" },
            { value: "leather", label: "Leather" },
            { value: "fur", label: "Fur / faux fur" },
            { value: "silk", label: "Silk (allergy/care)" },
            { value: "linen_wrinkle", label: "Linen (wrinkles bother me)" },
            { value: "none", label: "None" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Filter / penalty.",
        },
        {
          id: "modesty",
          prompt: "Cultural, religious, or modesty considerations?",
          type: "free_text",
          placeholder: "Optional, e.g. cover shoulders, knee-length minimum",
          skip_allowed: true,
          ask_later: false,
          rationale: "Hard rule. Respected unconditionally.",
        },
        {
          id: "allergies",
          prompt: "Allergies the stylist should know about?",
          type: "multi_select",
          options: [
            { value: "nickel", label: "Nickel (jewelry / hardware)" },
            { value: "wool", label: "Wool" },
            { value: "latex", label: "Latex" },
            { value: "fragrance", label: "Fragrance" },
            { value: "none", label: "None" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Skip items that trigger reactions.",
        },
      ],
    },
    {
      id: "wardrobe_relationship",
      title: "Your Closet Today",
      purpose:
        "How you actually use your wardrobe today — fixes and reinforces what the AI sees in your photos.",
      questions: [
        {
          id: "most_worn",
          prompt: "What are your 3 most-worn items right now?",
          type: "free_text",
          placeholder: "e.g. straight leg jeans, white tee, camel cardigan",
          skip_allowed: true,
          ask_later: false,
          rationale: "Direct lean-in: bias suggestions toward these and similar items.",
        },
        {
          id: "never_worn",
          prompt: "3 items you own but never wear, and why",
          type: "free_text",
          placeholder: "e.g. black blazer (too formal), green silk top (no occasion)",
          skip_allowed: true,
          ask_later: false,
          rationale: "Audit signal: deprioritize; surface why for the keep/donate review later.",
        },
        {
          id: "perceived_gaps",
          prompt: "What do you feel is missing from your wardrobe?",
          type: "free_text",
          placeholder: "e.g. great everyday flats, a non-jeans casual bottom",
          skip_allowed: true,
          ask_later: true,
          rationale: "Future: suggesting items to fill gaps.",
        },
        {
          id: "comfort_pattern",
          prompt: "How comfortable are you with bold prints / patterns?",
          type: "slider",
          min: 1,
          max: 5,
          skip_allowed: false,
          ask_later: false,
          rationale: "1 = solids only, 5 = layer patterns happily.",
        },
        {
          id: "comfort_color",
          prompt: "How comfortable are you with bold color?",
          type: "slider",
          min: 1,
          max: 5,
          skip_allowed: false,
          ask_later: false,
          rationale: "1 = neutrals only, 5 = saturated and bright.",
        },
        {
          id: "comfort_layering",
          prompt: "How comfortable are you with layering?",
          type: "slider",
          min: 1,
          max: 5,
          skip_allowed: false,
          ask_later: false,
          rationale: "1 = single-piece outfits, 5 = blazer + sweater + scarf.",
        },
        {
          id: "accessory_habits",
          prompt: "Which accessories do you actually wear?",
          type: "multi_select",
          options: [
            { value: "earrings", label: "Earrings" },
            { value: "necklaces", label: "Necklaces" },
            { value: "bracelets_rings", label: "Bracelets / rings" },
            { value: "scarves", label: "Scarves" },
            { value: "hats", label: "Hats" },
            { value: "belts", label: "Belts" },
            { value: "bags_statement", label: "Statement bags" },
            { value: "minimal", label: "I keep accessories minimal" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Tells the stylist whether to suggest finishing touches.",
        },
      ],
    },
    {
      id: "style_identity",
      title: "Your Style Identity",
      purpose:
        "Tone and vocabulary — how the AI describes outfits to you and which aesthetic to anchor on.",
      questions: [
        {
          id: "style_words",
          prompt: "Pick 3-5 words that describe the style you want to embody",
          type: "multi_select",
          options: [
            { value: "polished", label: "Polished" },
            { value: "feminine", label: "Feminine" },
            { value: "warm", label: "Warm" },
            { value: "minimal", label: "Minimal" },
            { value: "edgy", label: "Edgy" },
            { value: "romantic", label: "Romantic" },
            { value: "bohemian", label: "Bohemian" },
            { value: "classic", label: "Classic" },
            { value: "preppy", label: "Preppy" },
            { value: "sporty", label: "Sporty" },
            { value: "modern", label: "Modern" },
            { value: "eclectic", label: "Eclectic" },
            { value: "structured", label: "Structured" },
            { value: "drapey", label: "Drapey / soft" },
            { value: "embellished", label: "Embellished / detailed" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Anchors aesthetic and reasoning vocabulary in suggestions.",
        },
        {
          id: "style_words_other",
          prompt: "Other style words (free text)",
          type: "free_text",
          placeholder: "Anything we missed",
          skip_allowed: true,
          ask_later: false,
          rationale: "Catches words not in the list.",
        },
        {
          id: "style_icons",
          prompt: "Style icons or references whose closets you'd raid",
          type: "free_text",
          placeholder: "e.g. Hailey Bieber, Sofia Richie, an aunt, an Instagram account",
          skip_allowed: true,
          ask_later: false,
          rationale: "Powerful aesthetic anchor for the AI prompt.",
        },
        {
          id: "current_vs_aspirational",
          prompt: "Is the style you wear today the style you actually want?",
          type: "single_select",
          options: [
            { value: "yes_aligned", label: "Yes, basically aligned" },
            { value: "drift", label: "Mostly, but I want to push it further" },
            { value: "different", label: "No, my closet doesn't match my aspiration yet" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Tells the AI whether to play it safe (aligned) or stretch (aspirational).",
        },
        {
          id: "formality_range",
          prompt: "What formality range do you actually need? (pick the highest and lowest you wear)",
          type: "multi_select",
          options: [
            { value: "loungewear", label: "1 — Loungewear" },
            { value: "casual", label: "2 — Casual everyday" },
            { value: "smart_casual", label: "3 — Smart casual" },
            { value: "polished_office", label: "4 — Polished / office" },
            { value: "formal", label: "5 — Formal / black-tie" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Bounds for outfit formality. We won't suggest above your max or below your min.",
        },
        {
          id: "aesthetic_grid",
          prompt: "Pick the looks that resonate most (image grid in a future update)",
          type: "image_grid",
          options: [
            { value: "warm_polished", label: "Warm polished — drapey blouses + tailored bottoms" },
            { value: "minimal_modern", label: "Minimal modern — clean lines, neutrals" },
            { value: "boho_warm", label: "Boho warm — embroidery, smocking, earth tones" },
            { value: "classic_chic", label: "Classic chic — tailoring, refined" },
            { value: "edgy", label: "Edgy — leather, contrast, sharp" },
            { value: "romantic", label: "Romantic — florals, ruffles, soft" },
            { value: "sporty_chic", label: "Sporty chic — elevated athleisure" },
          ],
          skip_allowed: true,
          ask_later: false,
          rationale: "Visual anchor for aesthetic direction. (Will become real image grid.)",
        },
      ],
    },
    {
      id: "goals",
      title: "Goals & Mornings",
      purpose:
        "Defines the success criteria for daily suggestions and how you want to interact each morning.",
      questions: [
        {
          id: "jobs_to_be_done",
          prompt: "What's the top reason you want this app?",
          type: "multi_select",
          options: [
            { value: "decision_fatigue", label: "Reduce morning decision fatigue" },
            { value: "use_closet_better", label: "Actually wear what I already own" },
            { value: "look_more_put_together", label: "Look more put-together day-to-day" },
            { value: "stop_outfit_ruts", label: "Break out of my outfit ruts" },
            { value: "audit_closet", label: "Figure out what to keep vs let go of" },
            { value: "discover_combos", label: "Discover combinations I'd never think of" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Top jobs-to-be-done. Drives what to optimize for.",
        },
        {
          id: "great_outfit_day",
          prompt: "What does a great outfit day feel like for you?",
          type: "free_text",
          placeholder: "Describe the feeling — e.g. confident, comfortable, noticed, polished without trying",
          skip_allowed: true,
          ask_later: false,
          rationale: "Subjective signal — informs the voice and pickiness of the AI.",
        },
        {
          id: "outfit_ruts",
          prompt: "Recurring outfit ruts you fall into",
          type: "free_text",
          placeholder: "e.g. always default to jeans and a tee",
          skip_allowed: true,
          ask_later: false,
          rationale: "Tells the AI to push you out of these specifically.",
        },
        {
          id: "decision_speed",
          prompt: "How many outfit options do you want each morning?",
          type: "single_select",
          options: [
            { value: "one", label: "Just one — pick for me" },
            { value: "two_three", label: "2-3 options" },
            { value: "more", label: "Show me 4+ to pick from" },
          ],
          skip_allowed: false,
          ask_later: false,
          rationale: "Drives the morning UI.",
        },
        {
          id: "budget_mindset",
          prompt: "If we suggest items to fill gaps, what's your budget mindset?",
          type: "single_select",
          options: [
            { value: "investment", label: "Quality investment pieces, willing to spend" },
            { value: "midrange", label: "Mid-range — quality but not splurges" },
            { value: "thrifty", label: "Affordable / thrifty / secondhand" },
            { value: "no_suggestions", label: "Don't suggest items to buy" },
          ],
          skip_allowed: true,
          ask_later: true,
          rationale: "Future feature: closing wardrobe gaps with suggestions.",
        },
      ],
    },
  ],
};
